// Generated by gencpp from file gps_driver_pkg/gps_msg.msg
// DO NOT EDIT!


#ifndef GPS_DRIVER_PKG_MESSAGE_GPS_MSG_H
#define GPS_DRIVER_PKG_MESSAGE_GPS_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace gps_driver_pkg
{
template <class ContainerAllocator>
struct gps_msg_
{
  typedef gps_msg_<ContainerAllocator> Type;

  gps_msg_()
    : header()
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , UTM_easting(0.0)
    , UTM_northing(0.0)
    , Zone(0.0)
    , Letter()  {
    }
  gps_msg_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , latitude(0.0)
    , longitude(0.0)
    , altitude(0.0)
    , UTM_easting(0.0)
    , UTM_northing(0.0)
    , Zone(0.0)
    , Letter(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _latitude_type;
  _latitude_type latitude;

   typedef double _longitude_type;
  _longitude_type longitude;

   typedef double _altitude_type;
  _altitude_type altitude;

   typedef double _UTM_easting_type;
  _UTM_easting_type UTM_easting;

   typedef double _UTM_northing_type;
  _UTM_northing_type UTM_northing;

   typedef double _Zone_type;
  _Zone_type Zone;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Letter_type;
  _Letter_type Letter;





  typedef boost::shared_ptr< ::gps_driver_pkg::gps_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gps_driver_pkg::gps_msg_<ContainerAllocator> const> ConstPtr;

}; // struct gps_msg_

typedef ::gps_driver_pkg::gps_msg_<std::allocator<void> > gps_msg;

typedef boost::shared_ptr< ::gps_driver_pkg::gps_msg > gps_msgPtr;
typedef boost::shared_ptr< ::gps_driver_pkg::gps_msg const> gps_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gps_driver_pkg::gps_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::gps_driver_pkg::gps_msg_<ContainerAllocator1> & lhs, const ::gps_driver_pkg::gps_msg_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.latitude == rhs.latitude &&
    lhs.longitude == rhs.longitude &&
    lhs.altitude == rhs.altitude &&
    lhs.UTM_easting == rhs.UTM_easting &&
    lhs.UTM_northing == rhs.UTM_northing &&
    lhs.Zone == rhs.Zone &&
    lhs.Letter == rhs.Letter;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::gps_driver_pkg::gps_msg_<ContainerAllocator1> & lhs, const ::gps_driver_pkg::gps_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace gps_driver_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gps_driver_pkg::gps_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gps_driver_pkg::gps_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gps_driver_pkg::gps_msg_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "660b3faaa5bbe708e0b3557a47fdbec5";
  }

  static const char* value(const ::gps_driver_pkg::gps_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x660b3faaa5bbe708ULL;
  static const uint64_t static_value2 = 0xe0b3557a47fdbec5ULL;
};

template<class ContainerAllocator>
struct DataType< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gps_driver_pkg/gps_msg";
  }

  static const char* value(const ::gps_driver_pkg::gps_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 latitude\n"
"float64 longitude\n"
"float64 altitude\n"
"float64 UTM_easting\n"
"float64 UTM_northing\n"
"float64 Zone\n"
"string Letter\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::gps_driver_pkg::gps_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.latitude);
      stream.next(m.longitude);
      stream.next(m.altitude);
      stream.next(m.UTM_easting);
      stream.next(m.UTM_northing);
      stream.next(m.Zone);
      stream.next(m.Letter);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gps_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gps_driver_pkg::gps_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gps_driver_pkg::gps_msg_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "latitude: ";
    Printer<double>::stream(s, indent + "  ", v.latitude);
    s << indent << "longitude: ";
    Printer<double>::stream(s, indent + "  ", v.longitude);
    s << indent << "altitude: ";
    Printer<double>::stream(s, indent + "  ", v.altitude);
    s << indent << "UTM_easting: ";
    Printer<double>::stream(s, indent + "  ", v.UTM_easting);
    s << indent << "UTM_northing: ";
    Printer<double>::stream(s, indent + "  ", v.UTM_northing);
    s << indent << "Zone: ";
    Printer<double>::stream(s, indent + "  ", v.Zone);
    s << indent << "Letter: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Letter);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GPS_DRIVER_PKG_MESSAGE_GPS_MSG_H
